from pathlib import Path
p=Path(__file__).resolve().parents[2]/'context/scripts/build_wilmington_site.py'
s=p.read_text()
start=s.index('for name, slug, angle in areas:')
end=s.index('service_details = {', start)
new = r'''area_details = {
    'wilmington-nc': ('Port-city credibility has to feel current, not generic.', 'Wilmington buyers often move between historic local trust, coastal polish, and practical service expectations. Your online presence needs to feel clear, grounded, and easy to act on.', ['clear service explanations for Wilmington search intent', 'local proof and trust cues that fit port-city and coastal buyers', 'GBP, citations, and service pages that reinforce the same message'], ['home services and contractors', 'professional and appointment-based services', 'marine, coastal, and property-related services']),
    'leland-nc': ('Fast growth creates fast comparison.', 'Leland buyers are often newer to the area, comparing providers quickly, and looking for businesses that feel organized, responsive, and locally relevant.', ['service-area content that speaks to Leland growth', 'mobile-first lead paths for quote and consultation decisions', 'local SEO signals that connect Leland demand to the main service offer'], ['home services serving newer neighborhoods', 'family-focused local services', 'contractors and property services']),
    'carolina-beach-nc': ('Seasonal demand needs a page that gets to the point.', 'Carolina Beach searches often come with urgency, seasonality, and mobile-first behavior. Your online presence needs direct copy, easy contact paths, and a clear reason for customers to choose you.', ['clear offers for seasonal and local-service searches', 'conversion paths built for mobile decisions', 'AI-ready FAQs that answer practical buyer questions'], ['coastal property services', 'home maintenance and repair', 'appointment-based local services']),
    'wrightsville-beach-nc': ('Premium coastal buyers expect polish without fluff.', 'Wrightsville Beach buyers tend to reward clean presentation, strong trust signals, and quick clarity. Your online presence should feel refined but still practical.', ['higher-trust page design and copy', 'service explanations that support premium comparison', 'local relevance for coastal and property-focused searches'], ['premium home services', 'wellness and professional services', 'property, marine, and specialty providers']),
    'hampstead-nc': ('Growing suburban demand needs stronger local signals.', 'Hampstead is competitive because growth brings more providers and more search volume. Thin location mentions are easy for customers and search systems to ignore.', ['content that does more than mention Hampstead once', 'GBP and citation consistency for a growing service area', 'service pages that connect suburban demand to real lead paths'], ['home services and contractors', 'family-service businesses', 'appointment-based providers serving nearby communities']),
    'southport-nc': ('Trust and simplicity carry extra weight.', 'Southport buyers often value reputation, clarity, and an easy path to talk to someone. The page should feel steady, useful, and locally grounded.', ['plain-language explanations that reduce uncertainty', 'local trust framing for coastal and older-market buyers', 'structured content that supports search, maps, and AI summaries'], ['home and property services', 'professional services', 'coastal specialty providers']),
}
for name, slug, angle in areas:
    voice, buyer, strengths, fits = area_details[slug]
    strength_html = ''.join(f'<li>{x}</li>' for x in strengths)
    fit_html = ''.join(f'<li>{x}</li>' for x in fits)
    p = f"""<section class="hero"><div class="wrap"><p class="eyebrow">{name}, {STATE}</p><h1>Clearer digital visibility for {name} service businesses.</h1><p class="lead">{angle} {BRAND} helps {name}-area businesses turn scattered online signals into a clearer website, cleaner local presence, and stronger AI-search-ready explanation of what they do.</p><div class="actions"><a class="btn" href="/contact.html">Talk about {name}</a><a class="btn ghost" href="tel:{PHONE_E164}">Call {PHONE_DISPLAY}</a></div></div></section>
<section class="section"><div class="two"><article class="card"><p class="eyebrow">How local buyers decide</p><h2>{voice}</h2><p>{buyer}</p></article><article class="card"><p class="eyebrow">What we strengthen</p><h2>Better local signals across the whole lead path.</h2><ul>{strength_html}</ul></article></div></section>
<section class="section dark"><div><p class="eyebrow">Search, maps, and AI visibility</p><h2>{name} customers should find useful answers, not thin location copy.</h2><div class="cards"><article class="card"><h3>Service clarity</h3><p>We make it clear what you do, who you help, and which searches should lead customers to you.</p></article><article class="card"><h3>Local relevance</h3><p>Your local content connects the service to {name} buyer expectations, nearby demand, and the practical reasons someone would choose the business.</p></article><article class="card"><h3>Answer-ready structure</h3><p>Headings, FAQs, schema, and plain-language explanations help Google, maps, and AI systems understand your business without guessing.</p></article></div></div></section>
<section class="section"><div class="two"><article class="card"><p class="eyebrow">Who this helps most</p><h2>Where stronger local visibility can support real lead flow</h2><ul>{fit_html}</ul></article><article class="card"><p class="eyebrow">How your visibility compounds</p><h2>Your local visibility becomes part of the monthly marketing system.</h2><p>With the right local content in place, your Google Business Profile activity, citations, service pages, AI-search clarity, and paid landing pages all reinforce the same trust signals.</p><a class="btn" href="/contact.html">Start the {name} growth conversation</a></article></div></section>"""
    ROOT.joinpath('areas', f'{slug}-marketing-agency.html').write_text(layout(f'{name}, NC AI-Ready Marketing Agency | {BRAND}', f'AI-ready website, local SEO, Google Business Profile, Google Ads, and AI search visibility support for {name}, NC service businesses.', p, area_link(name, slug)))

'''
s=s[:start]+new+s[end:]
p.write_text(s)
print('expanded Port City area pages')
