from pathlib import Path

root = Path(__file__).resolve().parents[2]
script = root / 'context/scripts/build_wilmington_site.py'
s = script.read_text()

old_css = """:root{--ink:#10202a;--muted:#5a6a70;--bg:#f6fbfb;--card:#ffffff;--deep:#0e3b43;--teal:#176b73;--sea:#7fc8c2;--sand:#e7c98f;--line:#d8e8e6;--shadow:0 24px 70px rgba(16,32,42,.13)}*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,sans-serif;background:var(--bg);color:var(--ink);line-height:1.6}a{color:inherit}header{position:sticky;top:0;z-index:20;background:rgba(246,251,251,.92);backdrop-filter:blur(14px);border-bottom:1px solid var(--line)}.nav{max-width:1180px;margin:auto;padding:16px 22px;display:flex;align-items:center;justify-content:space-between;gap:18px}.brand{font-weight:900;letter-spacing:-.04em;font-size:1.28rem;display:flex;align-items:center;gap:10px}.mark{width:34px;height:34px;border-radius:12px;background:linear-gradient(135deg,var(--deep),var(--sea));box-shadow:inset 0 0 0 3px rgba(255,255,255,.35)}nav{display:flex;gap:16px;align-items:center;flex-wrap:wrap}nav a{text-decoration:none;color:#24454d;font-weight:750;font-size:.92rem}.phone,.btn{display:inline-flex;align-items:center;justify-content:center;border-radius:999px;padding:12px 18px;background:var(--deep);color:white;text-decoration:none;font-weight:850;box-shadow:0 12px 26px rgba(14,59,67,.22)}"""
new_css = """:root{--ink:#10202a;--muted:#5a6a70;--bg:#f6fbfb;--card:#ffffff;--deep:#0e3b43;--teal:#176b73;--sea:#7fc8c2;--sand:#e7c98f;--line:#d8e8e6;--shadow:0 24px 70px rgba(16,32,42,.13)}*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,sans-serif;background:var(--bg);color:var(--ink);line-height:1.6}a{color:inherit}header{position:sticky;top:0;z-index:20;background:rgba(246,251,251,.92);backdrop-filter:blur(14px);border-bottom:1px solid var(--line)}.nav{max-width:1180px;margin:auto;padding:16px 22px;display:flex;align-items:center;justify-content:space-between;gap:18px}.brand{font-weight:900;letter-spacing:-.04em;font-size:1.28rem;display:flex;align-items:center;gap:10px;text-decoration:none}.mark{width:38px;height:38px;border-radius:14px;background:#f6fbfb url('/favicon.svg') center/cover no-repeat;box-shadow:0 10px 22px rgba(14,59,67,.16),inset 0 0 0 1px rgba(14,59,67,.12)}.site-nav{display:flex;gap:16px;align-items:center;flex-wrap:wrap}.site-nav a{text-decoration:none;color:#24454d;font-weight:750;font-size:.92rem}.nav-toggle{display:none;border:1px solid var(--line);background:white;color:var(--deep);border-radius:999px;padding:10px 14px;font-weight:900}.phone,.btn{display:inline-flex;align-items:center;justify-content:center;border-radius:999px;padding:12px 18px;background:var(--deep);color:white;text-decoration:none;font-weight:850;box-shadow:0 12px 26px rgba(14,59,67,.22)}"""
s = s.replace(old_css, new_css)
s = s.replace("@media(max-width:850px){.grid,.two,.cards{grid-template-columns:1fr}.nav{align-items:flex-start;flex-direction:column}nav{display:none}.wrap{padding:54px 18px}.section{padding:54px 18px}h1{font-size:3rem}}", "@media(max-width:850px){.grid,.two,.cards{grid-template-columns:1fr}.nav{align-items:stretch;display:grid;grid-template-columns:1fr auto;gap:12px}.brand{min-width:0}.nav-toggle{display:inline-flex;align-items:center;justify-content:center}.site-nav{display:none;grid-column:1/-1;background:white;border:1px solid var(--line);border-radius:22px;padding:14px;box-shadow:var(--shadow)}.site-nav.open{display:grid;gap:8px}.site-nav a{padding:11px 12px;border-radius:14px;background:#f6fbfb}.phone{grid-column:1/-1;width:100%}.wrap{padding:54px 18px}.section{padding:54px 18px}h1{font-size:3rem}}")
old_layout = "<header><div class=\"nav\"><a class=\"brand\" href=\"/\"><span class=\"mark\"></span>{BRAND}</a><nav>{nav}<a href=\"/contact.html\">Contact</a></nav><a class=\"phone\" href=\"tel:{PHONE_E164}\">{PHONE_DISPLAY}</a></div></header>"
new_layout = "<header><div class=\"nav\"><a class=\"brand\" href=\"/\"><span class=\"mark\"></span>{BRAND}</a><button class=\"nav-toggle\" type=\"button\" aria-expanded=\"false\" aria-controls=\"site-nav\">Menu</button><nav id=\"site-nav\" class=\"site-nav\">{nav}<a href=\"/contact.html\">Contact</a></nav><a class=\"phone\" href=\"tel:{PHONE_E164}\">{PHONE_DISPLAY}</a></div></header>"
s = s.replace(old_layout, new_layout)
old_service = """for name, slug, desc in services:
    p = f'''<section class="hero"><div class="wrap"><p class="eyebrow">{name} in Wilmington</p><h1>{name} for Wilmington businesses that need to be found, trusted, and understood by AI search.</h1><p class="lead">{desc} {BRAND} keeps the work practical: stronger pages, clearer offers, local proof, structured FAQs, Google Business Profile alignment, and conversion paths that make the next step obvious.</p><div class="actions"><a class="btn" href="/contact.html">Ask how this works</a><a class="btn ghost" href="tel:{PHONE_E164}">Call {PHONE_DISPLAY}</a></div></div></section><section class="section"><div class="cards"><article class="card"><h3>Built for buyers</h3><p>Clear language, mobile-first layouts, visible contact paths, and trust signals that help real people decide faster.</p></article><article class="card"><h3>Built for search</h3><p>Local relevance, crawlable structure, focused headings, FAQs, and schema that support Google and answer-engine understanding.</p></article><article class="card"><h3>Built for follow-through</h3><p>Ads, SEO, GBP, citations, and website pages point in the same direction instead of acting like separate tactics.</p></article></div></section>'''
    ROOT.joinpath('services', f'{slug}.html').write_text(layout(f'{name} in Wilmington, NC | {BRAND}', f'{desc} Wilmington, NC support from {BRAND}.', p, service_link(slug)))
"""
new_service = """service_details = {
    'free-websites-wilmington-nc': ('A free build only works when it is tied to a real growth foundation.', ['No upfront design bill for qualified service businesses', 'Six-month growth partnership so research, structure, launch, and visibility work have enough runway', 'AI-ready page structure, FAQs, schema, and local proof included from the start'], 'Good fit for businesses that need a stronger first impression, clearer service pages, and better local visibility before spending harder on ads.'),
    'web-design-wilmington-nc': ('Your website should make your business easier to trust before someone calls.', ['Mobile-first layouts for fast coastal-market comparison', 'Service pages written around buyer questions, objections, and local proof', 'Conversion paths for calls, texts, and quote requests'], 'Good fit for dated sites, thin one-page websites, or businesses whose ads and GBP clicks are landing somewhere weak.'),
    'seo-ai-ranking-wilmington-nc': ('Local SEO now has to support maps, organic search, and AI-shaped answers.', ['Google Business Profile alignment and local entity clarity', 'FAQ and service content written for human decisions and answer engines', 'Citation cleanup, location relevance, and schema that stays conservative and supportable'], 'Good fit for businesses that want to be easier to understand across Google, maps, AI summaries, and comparison searches.'),
    'google-ads-wilmington-nc': ('Paid traffic works better when the landing page already earns trust.', ['Search campaigns pointed at focused service intent', 'Landing pages that match the offer, city, and buyer urgency', 'Call/text conversion paths and practical lead-quality feedback loops'], 'Good fit for businesses that need faster lead flow while the organic and AI visibility foundation compounds.'),
}
for name, slug, desc in services:
    detail_title, bullets, fit = service_details[slug]
    bullet_html = ''.join(f'<li>{b}</li>' for b in bullets)
    p = f'''<section class="hero"><div class="wrap"><p class="eyebrow">{name} in Wilmington</p><h1>{name} for Wilmington businesses that need to be found, trusted, and understood by AI search.</h1><p class="lead">{desc} {BRAND} keeps the work practical: stronger pages, clearer offers, local proof, structured FAQs, Google Business Profile alignment, and conversion paths that make the next step obvious.</p><div class="actions"><a class="btn" href="/contact.html">Ask how this works</a><a class="btn ghost" href="tel:{PHONE_E164}">Call {PHONE_DISPLAY}</a></div></div></section><section class="section"><div class="two"><article class="card"><p class="eyebrow">What you get</p><h2>{detail_title}</h2><ul>{bullet_html}</ul></article><article class="card"><p class="eyebrow">Best fit</p><h2>Where this helps most</h2><p>{fit}</p></article></div></section><section class="section"><div class="cards"><article class="card"><h3>Built for buyers</h3><p>Clear language, mobile-first layouts, visible contact paths, and trust signals that help real people decide faster.</p></article><article class="card"><h3>Built for search and AI</h3><p>Local relevance, crawlable structure, focused headings, FAQs, and schema that support Google and answer-engine understanding.</p></article><article class="card"><h3>Built for follow-through</h3><p>Ads, SEO, GBP, citations, and website pages point in the same direction instead of acting like separate tactics.</p></article></div></section>'''
    ROOT.joinpath('services', f'{slug}.html').write_text(layout(f'{name} in Wilmington, NC | {BRAND}', f'{desc} Wilmington, NC support from {BRAND}.', p, service_link(slug)))
"""
s = s.replace(old_service, new_service)
script.write_text(s)

app = root / 'app.js'
a = app.read_text()
a = a.replace("const nav = document.querySelector('.nav');", "const nav = document.querySelector('.site-nav');")
app.write_text(a)
print('patched generator and nav js')
